CREATE DATABASE Tegridy;
USE Tegridy;

-- Table 1: Users
CREATE TABLE IF NOT EXISTS Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    FirstName VARCHAR(45) NOT NULL,
    LastName VARCHAR(45) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Title VARCHAR(45) NOT NULL
);

-- Table 2: Cases
CREATE TABLE IF NOT EXISTS Cases (
    CaseID INT AUTO_INCREMENT PRIMARY KEY,
    CaseNumber VARCHAR(50) NOT NULL UNIQUE,
    Jurisdiction VARCHAR(100) NOT NULL,
    DateOpened DATE NOT NULL,
    DateClosed DATE,
    SuspectFirst VARCHAR(45) NOT NULL,
    SuspectLast VARCHAR(45) NOT NULL,
    CasePath VARCHAR(255) NOT NULL,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- Table 3: Evidence
CREATE TABLE IF NOT EXISTS Evidence (
    EvidenceID INT AUTO_INCREMENT PRIMARY KEY,
    FileType VARCHAR(50) NOT NULL,
    MD5Value VARCHAR(32) NOT NULL,
    MD5DateTime DATETIME NOT NULL,
    SHA1Value VARCHAR(40) NOT NULL,
    SHA1DateTime DATETIME NOT NULL,
    ItemPath VARCHAR(255) NOT NULL,
    CaseID INT NOT NULL,
    FOREIGN KEY (CaseID) REFERENCES Cases(CaseID)
);